create extension if not exists pg_trgm;

create table if not exists public.faq_history (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null,
  brand text not null,
  brand_name text not null,
  method text not null,
  path text not null,
  source text not null,
  user_id text,
  query text not null,
  query_normalized text,
  query_length integer not null default 0,
  matched boolean not null default false,
  score double precision not null default 0,
  faq_id text,
  faq_question text,
  category_id text,
  category_name text,
  answer_type text,
  selected_model text,
  metadata jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now()
);

create index if not exists idx_faq_history_occurred_at
  on public.faq_history (occurred_at desc);

create index if not exists idx_faq_history_brand_occurred_at
  on public.faq_history (brand, occurred_at desc);

create index if not exists idx_faq_history_source_occurred_at
  on public.faq_history (source, occurred_at desc);

create index if not exists idx_faq_history_faq_id
  on public.faq_history (faq_id);

create index if not exists idx_faq_history_category_id
  on public.faq_history (category_id);

create index if not exists idx_faq_history_selected_model
  on public.faq_history (selected_model)
  where selected_model is not null;

create index if not exists idx_faq_history_unmatched
  on public.faq_history (brand, occurred_at desc)
  where matched = false;

create index if not exists idx_faq_history_query_trgm
  on public.faq_history using gin (query_normalized gin_trgm_ops);

alter table public.faq_history enable row level security;

create or replace view public.faq_history_daily_summary as
select
  (occurred_at at time zone 'Asia/Seoul')::date as report_date,
  brand,
  brand_name,
  count(*) as total_count,
  count(*) filter (where matched) as matched_count,
  count(*) filter (where not matched) as unmatched_count,
  round((count(*) filter (where matched)::numeric / nullif(count(*), 0)) * 100, 2) as match_rate,
  count(distinct user_id) filter (where user_id is not null) as unique_user_count,
  round(avg(score)::numeric, 2) as avg_score
from public.faq_history
group by 1, 2, 3;

create or replace view public.faq_history_faq_summary as
select
  brand,
  brand_name,
  category_id,
  category_name,
  faq_id,
  faq_question,
  answer_type,
  selected_model,
  count(*) as hit_count,
  count(distinct user_id) filter (where user_id is not null) as unique_user_count,
  round(avg(score)::numeric, 2) as avg_score,
  min(occurred_at) as first_occurred_at,
  max(occurred_at) as last_occurred_at
from public.faq_history
where matched = true
group by 1, 2, 3, 4, 5, 6, 7, 8;

create or replace view public.faq_history_unmatched_queries as
select
  brand,
  brand_name,
  coalesce(nullif(query_normalized, ''), query) as query_key,
  min(query) as sample_query,
  count(*) as query_count,
  count(distinct user_id) filter (where user_id is not null) as unique_user_count,
  max(occurred_at) as last_occurred_at
from public.faq_history
where matched = false
group by 1, 2, 3;

comment on table public.faq_history is
  'FAQ chatbot request history for reporting, FAQ quality analysis, and web dashboards.';

comment on view public.faq_history_daily_summary is
  'Daily brand-level chatbot usage and match-rate summary.';

comment on view public.faq_history_faq_summary is
  'Matched FAQ hit counts for ranking frequently requested topics.';

comment on view public.faq_history_unmatched_queries is
  'Unmatched normalized queries for FAQ gap analysis.';
